# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestEditoradd():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_editoradd(self):
    self.driver.get("http://47.100.246.219/editor/")
    self.driver.set_window_size(1280, 800)
    self.driver.find_element(By.CSS_SELECTOR, ".el-input:nth-child(1) > .el-input__inner").click()
    self.driver.find_element(By.CSS_SELECTOR, ".el-input:nth-child(1) > .el-input__inner").send_keys("admin")
    self.driver.find_element(By.CSS_SELECTOR, ".el-input:nth-child(2) > .el-input__inner").send_keys("CostaAdmin")
    self.driver.find_element(By.ID, "signin").click()
    self.driver.execute_script("window.scrollTo(0,0)")
    self.driver.find_element(By.CSS_SELECTOR, ".el-table__row:nth-child(1) > .el-table_2_column_22 .el-button:nth-child(2) > span").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".el-table__row:nth-child(1) > .el-table_2_column_22 .el-button:nth-child(2) > span")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".el-message-box__btns > .el-button--primary > span").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".el-message-box__btns > .el-button--primary > span")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".button-color").click()
    self.driver.find_element(By.CSS_SELECTOR, ".avatar-uploader-icon").click()
    self.driver.find_element(By.CSS_SELECTOR, ".el-form-item:nth-child(4) .el-input__inner").click()
    self.driver.find_element(By.CSS_SELECTOR, ".el-form-item:nth-child(4) .el-input__inner").send_keys("上海")
    self.driver.find_element(By.CSS_SELECTOR, ".form-column-width2 .el-input__inner").send_keys("Shanghai")
    self.driver.find_element(By.CSS_SELECTOR, ".el-form-item:nth-child(7) .el-input__inner").click()
    self.driver.find_element(By.CSS_SELECTOR, ".el-form-item:nth-child(7) .el-input__inner").send_keys("晴")
    self.driver.find_element(By.CSS_SELECTOR, ".el-form-item:nth-child(8) .el-input__inner").send_keys("Sun")
    self.driver.find_element(By.CSS_SELECTOR, ".el-form-item:nth-child(8) .form-column-width").click()
    self.driver.find_element(By.CSS_SELECTOR, ".el-form-item:nth-child(9) .el-input__inner").click()
    self.driver.find_element(By.CSS_SELECTOR, ".el-form-item:nth-child(9) .el-input__inner").send_keys("20")
    self.driver.find_element(By.CSS_SELECTOR, ".el-form-item:nth-child(10) .el-input__inner").click()
    self.driver.find_element(By.CSS_SELECTOR, ".el-form-item:nth-child(10) .el-input__inner").send_keys("微浪")
    self.driver.find_element(By.CSS_SELECTOR, ".el-form-item:nth-child(11) .el-input__inner").send_keys("wave")
    self.driver.find_element(By.CSS_SELECTOR, ".el-input-number:nth-child(1) .el-input__inner").send_keys("10")
    self.driver.find_element(By.CSS_SELECTOR, ".el-input-number--small:nth-child(2) .el-input__inner").send_keys("20")
    self.driver.find_element(By.CSS_SELECTOR, ".el-form-item:nth-child(14) .el-input__inner").click()
    self.driver.find_element(By.CSS_SELECTOR, ".active:nth-child(9)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".confirm").click()
    self.driver.find_element(By.CSS_SELECTOR, ".el-form-item:nth-child(15) .el-input__inner").click()
    self.driver.find_element(By.CSS_SELECTOR, ".el-time-panel:nth-child(9) .confirm").click()
    self.driver.find_element(By.CSS_SELECTOR, ".el-form-item:nth-child(16) .el-input__inner").click()
    self.driver.find_element(By.CSS_SELECTOR, ".el-time-panel:nth-child(10) .confirm").click()
    self.driver.find_element(By.CSS_SELECTOR, ".el-form-item:nth-child(17) .el-input__inner").click()
    self.driver.find_element(By.CSS_SELECTOR, ".el-time-panel:nth-child(11) .el-time-spinner__wrapper:nth-child(1) .el-time-spinner__item:nth-child(7)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".el-time-panel:nth-child(11) .confirm").click()
    self.driver.find_element(By.CSS_SELECTOR, ".el-form-item:nth-child(18) .el-input__inner").click()
    self.driver.find_element(By.CSS_SELECTOR, ".el-time-panel:nth-child(12) .confirm").click()
    self.driver.find_element(By.CSS_SELECTOR, ".el-form-item:nth-child(20) .el-input__inner").click()
    self.driver.find_element(By.CSS_SELECTOR, ".hover > span").click()
    self.driver.find_element(By.CSS_SELECTOR, ".el-form-item:nth-child(20) .el-input__inner").click()
    self.driver.find_element(By.CSS_SELECTOR, ".hover").click()
    self.driver.find_element(By.CSS_SELECTOR, ".el-textarea__inner").click()
    self.driver.find_element(By.CSS_SELECTOR, ".el-textarea__inner").send_keys("这艘船非常棒")
    self.driver.find_element(By.CSS_SELECTOR, ".el-dialog__footer:nth-child(3) .el-button--primary > span").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".el-dialog__footer:nth-child(3) .el-button--primary > span")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
  
