# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestEditorcopy():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_editorcopy(self):
    # Test name: editor_copy
    # Step # | name | target | value
    # 1 | open | /editor/ | 
    self.driver.get("http://47.100.246.219/editor/")
    # 2 | setWindowSize | 1280x800 | 
    self.driver.set_window_size(1280, 800)
    # 3 | click | css=.el-table__row:nth-child(1) > .el-table_2_column_22 .el-button:nth-child(1) > span | 
    self.driver.find_element(By.CSS_SELECTOR, ".el-table__row:nth-child(1) > .el-table_2_column_22 .el-button:nth-child(1) > span").click()
    # 4 | click | css=.el-date-editor > .el-input__inner | 
    self.driver.find_element(By.CSS_SELECTOR, ".el-date-editor > .el-input__inner").click()
    # 5 | click | css=.el-date-table__row:nth-child(6) > .available:nth-child(4) span | 
    self.driver.find_element(By.CSS_SELECTOR, ".el-date-table__row:nth-child(6) > .available:nth-child(4) span").click()
    # 6 | click | css=.el-dialog__footer:nth-child(3) .el-button--default > span | 
    self.driver.find_element(By.CSS_SELECTOR, ".el-dialog__footer:nth-child(3) .el-button--default > span").click()
    # 7 | click | css=.el-table__row:nth-child(1) > .el-table_2_column_22 .el-button:nth-child(1) > span | 
    self.driver.find_element(By.CSS_SELECTOR, ".el-table__row:nth-child(1) > .el-table_2_column_22 .el-button:nth-child(1) > span").click()
    # 8 | click | css=.el-date-editor > .el-input__inner | 
    self.driver.find_element(By.CSS_SELECTOR, ".el-date-editor > .el-input__inner").click()
    # 9 | click | css=.el-date-table__row:nth-child(6) > .available:nth-child(4) span | 
    self.driver.find_element(By.CSS_SELECTOR, ".el-date-table__row:nth-child(6) > .available:nth-child(4) span").click()
    # 10 | click | css=.el-dialog__footer:nth-child(3) .el-button--primary > span | 
    self.driver.find_element(By.CSS_SELECTOR, ".el-dialog__footer:nth-child(3) .el-button--primary > span").click()
    # 11 | click | css=.el-dialog__footer:nth-child(3) .el-button--primary > span | 
    self.driver.find_element(By.CSS_SELECTOR, ".el-dialog__footer:nth-child(3) .el-button--primary > span").click()
    # 12 | click | css=.el-dialog__footer:nth-child(3) .el-button--primary > span | 
    self.driver.find_element(By.CSS_SELECTOR, ".el-dialog__footer:nth-child(3) .el-button--primary > span").click()
    # 13 | click | css=.el-dialog__footer:nth-child(3) .el-button--primary > span | 
    self.driver.find_element(By.CSS_SELECTOR, ".el-dialog__footer:nth-child(3) .el-button--primary > span").click()
    # 14 | click | css=.el-dialog__footer:nth-child(3) .el-button--primary > span | 
    self.driver.find_element(By.CSS_SELECTOR, ".el-dialog__footer:nth-child(3) .el-button--primary > span").click()
    # 15 | click | css=.el-dialog__footer:nth-child(3) .el-button--primary > span | 
    self.driver.find_element(By.CSS_SELECTOR, ".el-dialog__footer:nth-child(3) .el-button--primary > span").click()
    # 16 | click | css=.el-dialog__footer:nth-child(3) .el-button--primary > span | 
    self.driver.find_element(By.CSS_SELECTOR, ".el-dialog__footer:nth-child(3) .el-button--primary > span").click()
  
