# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestSignIn():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_signIn(self):
    self.driver.get("http://47.100.246.219/editor/")
    self.driver.set_window_size(828, 641)
    self.driver.find_element(By.CSS_SELECTOR, ".el-input:nth-child(1) > .el-input__inner").click()
    self.driver.find_element(By.CSS_SELECTOR, ".el-input:nth-child(1) > .el-input__inner").send_keys("dtp")
    self.driver.find_element(By.CSS_SELECTOR, ".el-form").click()
    self.driver.find_element(By.CSS_SELECTOR, ".el-input:nth-child(2) > .el-input__inner").click()
    self.driver.find_element(By.CSS_SELECTOR, ".el-input:nth-child(2) > .el-input__inner").send_keys("123456")
    self.driver.find_element(By.ID, "signin").click()
    assert self.driver.switch_to.alert.text == "The user name or password is wrong, please input again!"
    self.driver.find_element(By.CSS_SELECTOR, ".el-input:nth-child(1) > .el-input__inner").click()
    self.driver.find_element(By.CSS_SELECTOR, ".el-input:nth-child(1) > .el-input__inner").send_keys("")
    self.driver.find_element(By.CSS_SELECTOR, ".el-form").click()
    self.driver.find_element(By.CSS_SELECTOR, ".el-input:nth-child(2) > .el-input__inner").click()
    self.driver.find_element(By.CSS_SELECTOR, ".el-input:nth-child(2) > .el-input__inner").send_keys("CostaAdmin")
    self.driver.find_element(By.ID, "app").click()
    self.driver.find_element(By.ID, "signin").click()
    assert self.driver.switch_to.alert.text == "The user name or password is wrong, please input again!"
    self.driver.find_element(By.CSS_SELECTOR, ".el-input:nth-child(1) > .el-input__inner").click()
    self.driver.find_element(By.CSS_SELECTOR, ".el-input:nth-child(1) > .el-input__inner").send_keys("")
    self.driver.find_element(By.CSS_SELECTOR, ".el-form").click()
    self.driver.find_element(By.CSS_SELECTOR, ".el-input:nth-child(2) > .el-input__inner").click()
    self.driver.find_element(By.CSS_SELECTOR, ".el-input:nth-child(2) > .el-input__inner").send_keys("")
    self.driver.find_element(By.ID, "signin").click()
    assert self.driver.switch_to.alert.text == "The user name or password is wrong, please input again!"
    self.driver.find_element(By.CSS_SELECTOR, ".el-input:nth-child(1) > .el-input__inner").click()
    self.driver.find_element(By.CSS_SELECTOR, ".el-input:nth-child(1) > .el-input__inner").send_keys("dtp")
    self.driver.find_element(By.CSS_SELECTOR, ".el-form").click()
    self.driver.find_element(By.CSS_SELECTOR, ".el-input:nth-child(1) > .el-input__inner").click()
    self.driver.find_element(By.CSS_SELECTOR, ".el-input:nth-child(2) > .el-input__inner").send_keys("")
    self.driver.find_element(By.ID, "signin").click()
    assert self.driver.switch_to.alert.text == "The user name or password is wrong, please input again!"
    self.driver.find_element(By.CSS_SELECTOR, ".el-input:nth-child(1) > .el-input__inner").click()
    self.driver.find_element(By.CSS_SELECTOR, ".el-input:nth-child(1) > .el-input__inner").send_keys("dtp")
    self.driver.find_element(By.CSS_SELECTOR, ".el-form").click()
    self.driver.find_element(By.CSS_SELECTOR, ".el-input:nth-child(2) > .el-input__inner").click()
    self.driver.find_element(By.CSS_SELECTOR, ".el-input:nth-child(2) > .el-input__inner").send_keys("Costa@Admin")
    self.driver.find_element(By.ID, "signin").click()
    assert self.driver.switch_to.alert.text == "The user name or password is wrong, please input again!"
    self.driver.find_element(By.CSS_SELECTOR, ".el-input:nth-child(1) > .el-input__inner").click()
    self.driver.find_element(By.CSS_SELECTOR, ".el-input:nth-child(1) > .el-input__inner").send_keys("admin")
    self.driver.find_element(By.CSS_SELECTOR, ".el-form").click()
    self.driver.find_element(By.CSS_SELECTOR, ".el-input:nth-child(2) > .el-input__inner").click()
    self.driver.find_element(By.CSS_SELECTOR, ".el-input:nth-child(2) > .el-input__inner").click()
    self.driver.find_element(By.CSS_SELECTOR, ".el-input:nth-child(2) > .el-input__inner").send_keys("123456")
    self.driver.find_element(By.ID, "signin").click()
    assert self.driver.switch_to.alert.text == "Sorry, no permission"
    self.driver.find_element(By.CSS_SELECTOR, ".el-input:nth-child(1) > .el-input__inner").click()
    self.driver.find_element(By.CSS_SELECTOR, ".el-input:nth-child(1) > .el-input__inner").send_keys("dtp@new")
    self.driver.find_element(By.CSS_SELECTOR, ".el-form").click()
    self.driver.find_element(By.CSS_SELECTOR, ".el-input:nth-child(2) > .el-input__inner").click()
    self.driver.find_element(By.CSS_SELECTOR, ".el-input:nth-child(2) > .el-input__inner").send_keys("CostaAdmin")
    self.driver.find_element(By.ID, "signin").click()
    assert self.driver.switch_to.alert.text == "Sorry, no permission"
    self.driver.find_element(By.CSS_SELECTOR, ".el-input:nth-child(1) > .el-input__inner").click()
    self.driver.find_element(By.CSS_SELECTOR, ".el-input:nth-child(1) > .el-input__inner").send_keys("admin")
    self.driver.find_element(By.CSS_SELECTOR, ".el-form").click()
    self.driver.find_element(By.CSS_SELECTOR, ".el-input:nth-child(2) > .el-input__inner").click()
    self.driver.find_element(By.CSS_SELECTOR, ".el-input:nth-child(2) > .el-input__inner").send_keys("CostaAdmin")
    self.driver.find_element(By.ID, "signin").click()
    self.driver.execute_script("window.scrollTo(0,0)")