# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestSignIn():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_signIn(self):
    # Test name: Sign In
    # Step # | name | target | value
    # 1 | open | /editor/ | 
    self.driver.get("http://47.100.246.219/editor/")
    # 2 | setWindowSize | 828x641 | 
    self.driver.set_window_size(828, 641)
    # 3 | click | css=.el-input:nth-child(1) > .el-input__inner | 
    self.driver.find_element(By.CSS_SELECTOR, ".el-input:nth-child(1) > .el-input__inner").click()
    # 4 | type | css=.el-input:nth-child(1) > .el-input__inner | dtp
    self.driver.find_element(By.CSS_SELECTOR, ".el-input:nth-child(1) > .el-input__inner").send_keys("dtp")
    # 5 | click | css=.el-form | 
    self.driver.find_element(By.CSS_SELECTOR, ".el-form").click()
    # 6 | click | css=.el-input:nth-child(2) > .el-input__inner | 
    self.driver.find_element(By.CSS_SELECTOR, ".el-input:nth-child(2) > .el-input__inner").click()
    # 7 | type | css=.el-input:nth-child(2) > .el-input__inner | 123456
    self.driver.find_element(By.CSS_SELECTOR, ".el-input:nth-child(2) > .el-input__inner").send_keys("123456")
    # 8 | click | id=signin | 
    self.driver.find_element(By.ID, "signin").click()
    # 9 | assertAlert | The user name or password is wrong, please input again! | 
    assert self.driver.switch_to.alert.text == "The user name or password is wrong, please input again!"
    # 10 | click | css=.el-input:nth-child(1) > .el-input__inner | 
    self.driver.find_element(By.CSS_SELECTOR, ".el-input:nth-child(1) > .el-input__inner").click()
    # | type | css=.el-input:nth-child(1) > .el-input__inner | 空格
    self.driver.find_element(By.CSS_SELECTOR, ".el-input:nth-child(1) > .el-input__inner").send_keys("")
    # 11 | click | css=.el-form | 
    self.driver.find_element(By.CSS_SELECTOR, ".el-form").click()
    # 12 | click | css=.el-input:nth-child(2) > .el-input__inner | 
    self.driver.find_element(By.CSS_SELECTOR, ".el-input:nth-child(2) > .el-input__inner").click()
    # 13 | type | css=.el-input:nth-child(2) > .el-input__inner | 12345678
    self.driver.find_element(By.CSS_SELECTOR, ".el-input:nth-child(2) > .el-input__inner").send_keys("CostaAdmin")
    # 14 | click | id=app | 
    self.driver.find_element(By.ID, "app").click()
    # 15 | click | id=signin | 
    self.driver.find_element(By.ID, "signin").click()
    # 16 | assertAlert | The user name or password is wrong, please input again! | 
    assert self.driver.switch_to.alert.text == "The user name or password is wrong, please input again!"
    # 17 | click | css=.el-input:nth-child(1) > .el-input__inner | 
    self.driver.find_element(By.CSS_SELECTOR, ".el-input:nth-child(1) > .el-input__inner").click()
    # | type | css=.el-input:nth-child(1) > .el-input__inner | 空格
    self.driver.find_element(By.CSS_SELECTOR, ".el-input:nth-child(1) > .el-input__inner").send_keys("")
    # 18 | click | css=.el-form | 
    self.driver.find_element(By.CSS_SELECTOR, ".el-form").click()
    # 19 | click | css=.el-input:nth-child(2) > .el-input__inner | 
    self.driver.find_element(By.CSS_SELECTOR, ".el-input:nth-child(2) > .el-input__inner").click()
    # 20 | type | css=.el-input:nth-child(2) > .el-input__inner |
    self.driver.find_element(By.CSS_SELECTOR, ".el-input:nth-child(2) > .el-input__inner").send_keys("")
    # 21 | click | id=signin | 
    self.driver.find_element(By.ID, "signin").click()
    # 22 | assertAlert | The user name or password is wrong, please input again! | 
    assert self.driver.switch_to.alert.text == "The user name or password is wrong, please input again!"
    # 23 | click | css=.el-input:nth-child(1) > .el-input__inner | 
    self.driver.find_element(By.CSS_SELECTOR, ".el-input:nth-child(1) > .el-input__inner").click()
    # 4 | type | css=.el-input:nth-child(1) > .el-input__inner | dtp
    self.driver.find_element(By.CSS_SELECTOR, ".el-input:nth-child(1) > .el-input__inner").send_keys("dtp")
    # 24 | click | css=.el-form | 
    self.driver.find_element(By.CSS_SELECTOR, ".el-form").click()
    # 25 | click | css=.el-input:nth-child(1) > .el-input__inner | 
    self.driver.find_element(By.CSS_SELECTOR, ".el-input:nth-child(1) > .el-input__inner").click()
    # 20 | type | css=.el-input:nth-child(2) > .el-input__inner |
    self.driver.find_element(By.CSS_SELECTOR, ".el-input:nth-child(2) > .el-input__inner").send_keys("")
    self.driver.find_element(By.ID, "signin").click()
    # 30 | assertAlert | The user name or password is wrong, please input again! | 
    assert self.driver.switch_to.alert.text == "The user name or password is wrong, please input again!"
    # 31 | click | css=.el-input:nth-child(1) > .el-input__inner | 
    self.driver.find_element(By.CSS_SELECTOR, ".el-input:nth-child(1) > .el-input__inner").click()
    # 32 | type | css=.el-input:nth-child(1) > .el-input__inner | dtp-new
    self.driver.find_element(By.CSS_SELECTOR, ".el-input:nth-child(1) > .el-input__inner").send_keys("dtp")
    # 33 | click | css=.el-form | 
    self.driver.find_element(By.CSS_SELECTOR, ".el-form").click()
    # 34 | click | css=.el-input:nth-child(2) > .el-input__inner | 
    self.driver.find_element(By.CSS_SELECTOR, ".el-input:nth-child(2) > .el-input__inner").click()
    # 35 | type | css=.el-input:nth-child(2) > .el-input__inner | CostaAdmin
    self.driver.find_element(By.CSS_SELECTOR, ".el-input:nth-child(2) > .el-input__inner").send_keys("Costa@Admin")
    # 36 | click | id=signin | 
    self.driver.find_element(By.ID, "signin").click()
    # 37 | assertAlert | Sorry, no permission | 
    assert self.driver.switch_to.alert.text == "The user name or password is wrong, please input again!"
    # 38 | click | css=.el-input:nth-child(1) > .el-input__inner | 
    self.driver.find_element(By.CSS_SELECTOR, ".el-input:nth-child(1) > .el-input__inner").click()
    # 39 | type | css=.el-input:nth-child(1) > .el-input__inner | admin
    self.driver.find_element(By.CSS_SELECTOR, ".el-input:nth-child(1) > .el-input__inner").send_keys("admin")
    # 40 | click | css=.el-form | 
    self.driver.find_element(By.CSS_SELECTOR, ".el-form").click()
    # 41 | click | css=.el-input:nth-child(2) > .el-input__inner | 
    self.driver.find_element(By.CSS_SELECTOR, ".el-input:nth-child(2) > .el-input__inner").click()
    # 42 | click | css=.el-input:nth-child(2) > .el-input__inner | 
    self.driver.find_element(By.CSS_SELECTOR, ".el-input:nth-child(2) > .el-input__inner").click()
    # 43 | type | css=.el-input:nth-child(2) > .el-input__inner | 123456
    self.driver.find_element(By.CSS_SELECTOR, ".el-input:nth-child(2) > .el-input__inner").send_keys("123456")
    # 44 | click | id=signin | 
    self.driver.find_element(By.ID, "signin").click()
    # 45 | assertAlert | Sorry, no permission | 
    assert self.driver.switch_to.alert.text == "Sorry, no permission"
    # 46 | click | css=.el-input:nth-child(1) > .el-input__inner | 
    self.driver.find_element(By.CSS_SELECTOR, ".el-input:nth-child(1) > .el-input__inner").click()
    # 47 | type | css=.el-input:nth-child(1) > .el-input__inner | dtp
    self.driver.find_element(By.CSS_SELECTOR, ".el-input:nth-child(1) > .el-input__inner").send_keys("dtp@new")
    # 48 | click | css=.el-form | 
    self.driver.find_element(By.CSS_SELECTOR, ".el-form").click()
    # 49 | click | css=.el-input:nth-child(2) > .el-input__inner | 
    self.driver.find_element(By.CSS_SELECTOR, ".el-input:nth-child(2) > .el-input__inner").click()
    # 50 | type | css=.el-input:nth-child(2) > .el-input__inner | 123456789
    self.driver.find_element(By.CSS_SELECTOR, ".el-input:nth-child(2) > .el-input__inner").send_keys("CostaAdmin")
    # 51 | click | id=signin | 
    self.driver.find_element(By.ID, "signin").click()
    # 52 | assertAlert | The user name or password is wrong, please input again! | 
    assert self.driver.switch_to.alert.text == "Sorry, no permission"
    # 53 | click | css=.el-input:nth-child(1) > .el-input__inner | 
    self.driver.find_element(By.CSS_SELECTOR, ".el-input:nth-child(1) > .el-input__inner").click()
    # 54 | type | css=.el-input:nth-child(1) > .el-input__inner | admin
    self.driver.find_element(By.CSS_SELECTOR, ".el-input:nth-child(1) > .el-input__inner").send_keys("admin")
    # 55 | click | css=.el-form | 
    self.driver.find_element(By.CSS_SELECTOR, ".el-form").click()
    # 56 | click | css=.el-input:nth-child(2) > .el-input__inner | 
    self.driver.find_element(By.CSS_SELECTOR, ".el-input:nth-child(2) > .el-input__inner").click()
    # 57 | type | css=.el-input:nth-child(2) > .el-input__inner | CostaAdmin
    self.driver.find_element(By.CSS_SELECTOR, ".el-input:nth-child(2) > .el-input__inner").send_keys("CostaAdmin")
    # 58 | click | id=signin | 
    self.driver.find_element(By.ID, "signin").click()
    # 59 | runScript | window.scrollTo(0,0) | 
    self.driver.execute_script("window.scrollTo(0,0)")
  
