# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestEditoredit():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_editoredit(self):
    # Test name: editor_edit
    # Step # | name | target | value
    # 1 | open | /editor/ | 
    self.driver.get("http://47.100.246.219/editor/")
    # 2 | setWindowSize | 1280x800 | 
    self.driver.set_window_size(1280, 800)
    # 3 | click | css=.el-table__row:nth-child(1) > .el-table_2_column_20 span | 
    self.driver.find_element(By.CSS_SELECTOR, ".el-table__row:nth-child(1) > .el-table_2_column_20 span").click()
    # 4 | click | css=.el-form-item:nth-child(4) .el-input__inner | 
    self.driver.find_element(By.CSS_SELECTOR, ".el-form-item:nth-child(4) .el-input__inner").click()
    # 5 | type | css=.el-form-item:nth-child(4) .el-input__inner | 上海修
    self.driver.find_element(By.CSS_SELECTOR, ".el-form-item:nth-child(4) .el-input__inner").send_keys("上海修")
    # 6 | click | css=.form-column-width2 .el-input__inner | 
    self.driver.find_element(By.CSS_SELECTOR, ".form-column-width2 .el-input__inner").click()
    # 7 | type | css=.form-column-width2 .el-input__inner | Shanghai_xiu
    self.driver.find_element(By.CSS_SELECTOR, ".form-column-width2 .el-input__inner").send_keys("Shanghai_xiu")
    # 8 | click | css=.el-form-item:nth-child(7) .el-input__inner | 
    self.driver.find_element(By.CSS_SELECTOR, ".el-form-item:nth-child(7) .el-input__inner").click()
    # 9 | type | css=.el-form-item:nth-child(7) .el-input__inner | 晴_xiu
    self.driver.find_element(By.CSS_SELECTOR, ".el-form-item:nth-child(7) .el-input__inner").send_keys("晴_xiu")
    # 10 | click | css=.el-form-item:nth-child(8) .el-input__inner | 
    self.driver.find_element(By.CSS_SELECTOR, ".el-form-item:nth-child(8) .el-input__inner").click()
    # 11 | type | css=.el-form-item:nth-child(8) .el-input__inner | Sun_edit
    self.driver.find_element(By.CSS_SELECTOR, ".el-form-item:nth-child(8) .el-input__inner").send_keys("Sun_edit")
    # 12 | click | css=.el-form-item:nth-child(9) .el-input__inner | 
    self.driver.find_element(By.CSS_SELECTOR, ".el-form-item:nth-child(9) .el-input__inner").click()
    # 13 | type | css=.el-form-item:nth-child(9) .el-input__inner | 21
    self.driver.find_element(By.CSS_SELECTOR, ".el-form-item:nth-child(9) .el-input__inner").send_keys("21")
    # 14 | click | css=.el-form-item:nth-child(10) .el-input__inner | 
    self.driver.find_element(By.CSS_SELECTOR, ".el-form-item:nth-child(10) .el-input__inner").click()
    # 15 | click | css=.el-form-item:nth-child(10) .el-input__inner | 
    self.driver.find_element(By.CSS_SELECTOR, ".el-form-item:nth-child(10) .el-input__inner").click()
    # 16 | type | css=.el-form-item:nth-child(10) .el-input__inner | 微微浪
    self.driver.find_element(By.CSS_SELECTOR, ".el-form-item:nth-child(10) .el-input__inner").send_keys("微微浪")
    # 17 | click | css=.el-form-item:nth-child(11) .el-input__inner | 
    self.driver.find_element(By.CSS_SELECTOR, ".el-form-item:nth-child(11) .el-input__inner").click()
    # 18 | click | css=.el-form-item:nth-child(11) .el-input__inner | 
    self.driver.find_element(By.CSS_SELECTOR, ".el-form-item:nth-child(11) .el-input__inner").click()
    # 19 | type | css=.el-form-item:nth-child(11) .el-input__inner | littlewave
    self.driver.find_element(By.CSS_SELECTOR, ".el-form-item:nth-child(11) .el-input__inner").send_keys("littlewave")
    # 20 | click | css=.el-input-number:nth-child(1) .el-icon-plus | 
    self.driver.find_element(By.CSS_SELECTOR, ".el-input-number:nth-child(1) .el-icon-plus").click()
    # 21 | click | css=.el-input-number:nth-child(1) .el-icon-plus | 
    self.driver.find_element(By.CSS_SELECTOR, ".el-input-number:nth-child(1) .el-icon-plus").click()
    # 22 | click | css=.el-form-item:nth-child(14) .el-input__inner | 
    self.driver.find_element(By.CSS_SELECTOR, ".el-form-item:nth-child(14) .el-input__inner").click()
    # 23 | click | css=.el-time-spinner__wrapper:nth-child(1) .el-time-spinner__item:nth-child(10) | 
    self.driver.find_element(By.CSS_SELECTOR, ".el-time-spinner__wrapper:nth-child(1) .el-time-spinner__item:nth-child(10)").click()
    # 24 | click | css=.confirm | 
    self.driver.find_element(By.CSS_SELECTOR, ".confirm").click()
    # 25 | click | css=.el-form-item:nth-child(15) .el-input__inner | 
    self.driver.find_element(By.CSS_SELECTOR, ".el-form-item:nth-child(15) .el-input__inner").click()
    # 26 | click | css=.el-time-panel:nth-child(8) .el-time-spinner__wrapper:nth-child(1) .el-time-spinner__item:nth-child(23) | 
    self.driver.find_element(By.CSS_SELECTOR, ".el-time-panel:nth-child(8) .el-time-spinner__wrapper:nth-child(1) .el-time-spinner__item:nth-child(23)").click()
    # 27 | click | css=.el-time-panel:nth-child(8) .confirm | 
    self.driver.find_element(By.CSS_SELECTOR, ".el-time-panel:nth-child(8) .confirm").click()
    # 28 | click | css=.el-form-item:nth-child(16) .el-input__inner | 
    self.driver.find_element(By.CSS_SELECTOR, ".el-form-item:nth-child(16) .el-input__inner").click()
    # 29 | click | css=.el-time-panel:nth-child(9) .el-time-spinner__wrapper:nth-child(1) .el-time-spinner__item:nth-child(23) | 
    self.driver.find_element(By.CSS_SELECTOR, ".el-time-panel:nth-child(9) .el-time-spinner__wrapper:nth-child(1) .el-time-spinner__item:nth-child(23)").click()
    # 30 | click | css=.el-time-panel:nth-child(9) .confirm | 
    self.driver.find_element(By.CSS_SELECTOR, ".el-time-panel:nth-child(9) .confirm").click()
    # 31 | click | css=.el-form-item:nth-child(17) .el-input__inner | 
    self.driver.find_element(By.CSS_SELECTOR, ".el-form-item:nth-child(17) .el-input__inner").click()
    # 32 | click | css=.el-time-panel:nth-child(10) .el-time-spinner__wrapper:nth-child(2) .el-time-spinner__item:nth-child(29) | 
    self.driver.find_element(By.CSS_SELECTOR, ".el-time-panel:nth-child(10) .el-time-spinner__wrapper:nth-child(2) .el-time-spinner__item:nth-child(29)").click()
    # 33 | click | css=.el-time-panel:nth-child(10) .confirm | 
    self.driver.find_element(By.CSS_SELECTOR, ".el-time-panel:nth-child(10) .confirm").click()
    # 34 | click | css=.el-form-item:nth-child(18) .el-input__inner | 
    self.driver.find_element(By.CSS_SELECTOR, ".el-form-item:nth-child(18) .el-input__inner").click()
    # 35 | click | css=.el-time-panel:nth-child(11) .el-time-spinner__wrapper:nth-child(2) .el-time-spinner__item:nth-child(33) | 
    self.driver.find_element(By.CSS_SELECTOR, ".el-time-panel:nth-child(11) .el-time-spinner__wrapper:nth-child(2) .el-time-spinner__item:nth-child(33)").click()
    # 36 | click | css=.el-time-panel:nth-child(11) .confirm | 
    self.driver.find_element(By.CSS_SELECTOR, ".el-time-panel:nth-child(11) .confirm").click()
    # 37 | click | css=.el-textarea__inner | 
    self.driver.find_element(By.CSS_SELECTOR, ".el-textarea__inner").click()
    # 38 | type | css=.el-textarea__inner | 这艘船非常棒，非常棒
    self.driver.find_element(By.CSS_SELECTOR, ".el-textarea__inner").send_keys("这艘船非常棒，非常棒")
    # 39 | click | css=.el-dialog__footer:nth-child(3) .el-button--primary > span | 
    self.driver.find_element(By.CSS_SELECTOR, ".el-dialog__footer:nth-child(3) .el-button--primary > span").click()
    # 40 | mouseOver | css=.el-dialog__footer:nth-child(3) .el-button--primary > span | 
    element = self.driver.find_element(By.CSS_SELECTOR, ".el-dialog__footer:nth-child(3) .el-button--primary > span")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
  
