# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestEditordel():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_editordel(self):
    # Test name: editor_del
    # Step # | name | target | value
    # 1 | open | /editor/ | 
    self.driver.get("http://47.100.246.219/editor/")
    # 2 | setWindowSize | 1280x800 | 
    self.driver.set_window_size(1280, 800)
    # 3 | click | css=.el-table__row:nth-child(2) > .el-table_2_column_22 .el-button:nth-child(2) > span | 
    self.driver.find_element(By.CSS_SELECTOR, ".el-table__row:nth-child(2) > .el-table_2_column_22 .el-button:nth-child(2) > span").click()
    # 4 | click | css=.el-button--default:nth-child(1) > span | 
    self.driver.find_element(By.CSS_SELECTOR, ".el-button--default:nth-child(1) > span").click()
    # 5 | click | css=.el-message-box__wrapper | 
    self.driver.find_element(By.CSS_SELECTOR, ".el-message-box__wrapper").click()
    # 6 | click | css=.el-table__row:nth-child(2) > .el-table_2_column_22 .el-button:nth-child(2) > span | 
    self.driver.find_element(By.CSS_SELECTOR, ".el-table__row:nth-child(2) > .el-table_2_column_22 .el-button:nth-child(2) > span").click()
    # 7 | mouseOver | css=.el-table__row:nth-child(2) > .el-table_2_column_22 .el-button:nth-child(2) > span | 
    element = self.driver.find_element(By.CSS_SELECTOR, ".el-table__row:nth-child(2) > .el-table_2_column_22 .el-button:nth-child(2) > span")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 8 | mouseOut | css=.el-table__row:nth-child(2) > .el-table_2_column_22 .el-button:nth-child(2) > span | 
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    # 9 | click | css=.el-message-box__btns > .el-button--primary > span | 
    self.driver.find_element(By.CSS_SELECTOR, ".el-message-box__btns > .el-button--primary > span").click()
  
